## Numpy

### Theoretical Questions:

#### 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

NumPy is a Python library that makes working with numbers and data easier and faster, especially when dealing with large amounts of data. Here's a simpler explanation of its purpose, advantages, and how it improves Python for numerical tasks:



##### Purpose of NumPy:

+ Efficient Arrays: NumPy provides a special type of data structure called an "array" (like a list but better for numbers) that can handle large amounts of data quickly.
+ Math Tools: It gives you a set of tools to do mathematical calculations easily, like adding, multiplying, or performing more complex tasks with many numbers.
+ Data Storage: NumPy arrays use less memory and work faster than regular Python lists, which is important when handling big datasets.
+ Foundation for Other Libraries: Many popular data analysis tools, like Pandas and SciPy, are built on top of NumPy, using its arrays to speed things up.

##### Advantages of NumPy:

+ Speed: NumPy is much faster than regular Python lists because it's written in C, a low-level language that's very fast for numerical tasks.

+ Vectorized Operations: You can perform operations on whole arrays at once (like adding or multiplying numbers) without writing a loop, making the code shorter and faster.

+ Multidimensional Arrays: It can handle multi-dimensional data (like 2D arrays for images or 3D arrays for videos), which is important for scientific work or machine learning.

+ Broadcasting: NumPy can automatically handle arrays of different sizes and shapes, saving time by reducing the need to manually adjust data for calculations.

+ Math Functions: It includes many built-in functions to handle complex math, like matrix operations and statistics, making it very useful for science and data analysis.



##### How NumPy Enhances Python:

+ Better for Big Data: Python’s built-in lists are flexible but slow for numerical tasks. NumPy arrays are specifically designed to handle large amounts of numbers quickly.

+ Memory Efficiency: NumPy uses less memory, so you can work with bigger datasets without running out of space.

+ Easy Data Manipulation: It lets you easily reshape and filter data, making it much simpler to work with large datasets in fields like data science and machine learning.

+ Parallel Processing: NumPy can sometimes use multiple processors at once, speeding up computations.

 NumPy makes Python much more powerful for working with numbers and data, helping scientists, data analysts, and engineers do their work faster and more efficiently.

#### 2. Compare and contrast np.mean()b and np.average() functions in NumPy. When would you use  one over the other? 

In NumPy, both `np.mean()` and `np.average()` are used to calculate the average of numbers in an array, but they have some differences. Here's a simple comparison:

##### `np.mean():`

+ Purpose: This function calculates the simple arithmetic mean (average) of an array. It adds up all the numbers and divides by the number of items.
+ Usage: You would use np.mean() when you want to find the plain average of a set of numbers without any special adjustments.

##### `np.average():`

+ Purpose: This function also calculates the average, but with an added feature: you can give weights to the numbers. This means that some numbers can count more or less in the calculation.
+ Usage: You would use np.average() when you want to calculate a weighted average, where certain values are more important than others.

##### Key Differences:

##### 1. Weights:

+ `np.mean()` does not use weights; it gives equal importance to all values.
+ `np.average()` can use weights, allowing certain numbers to have more or less influence on 

##### 2. Default Behavior:

+ If you just want a simple average, np.mean() is the go-to function.
+ If you need a weighted average, you should use np.average().


##### When to Use Each:

+ Use np.mean() when you want the plain, unweighted average of numbers.
+ Use np.average() when you need to factor in weights, giving different values different levels of importance in the calculation.

#### 3. Describe the methods for reversing a NumPy array along different axes. Provide Examples for 1D and 2D array.

To reverse a NumPy array along different axes, you can use slicing or built-in NumPy functions. Here’s how to do it for 1D and 2D arrays:

##### 1D Array (Single Axis):

To reverse a 1D array, you can simply use slicing with `[::-1]`.

##### Example:

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)  # Output: [5 4 3 2 1]


##### 2D Array (Rows or Columns):


For 2D arrays, you can reverse along rows or columns using slicing on different axes:

+ Reverse Rows (axis 0): Use `[::-1, :]` to reverse the order of the rows.
+ Reverse Columns (axis 1): Use `[:, ::-1]` to reverse the order of the columns.

##### Example:

In [ ]:
import numpy as np
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Reverse Rows
reversed_rows = arr_2d[::-1, :]
print(reversed_rows)  
# Output: 
# [[7 8 9]
#  [4 5 6]
#  [1 2 3]]

# Reverse Columns
reversed_cols = arr_2d[:, ::-1]
print(reversed_cols)
# Output: 
# [[3 2 1]
#  [6 5 4]
#  [9 8 7]]


Summary:
+ Use `[::-1]` for reversing a 1D array.
+ Use `[::-1, :]` for reversing rows in a 2D array.
+ Use `[:, ::-1]` for reversing columns in a 2D array.







#### 4. How can you determine the data types of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

##### Determining Data Types in a NumPy Array:

To determine the data type of elements in a NumPy array, you can use the .dtype attribute.

##### Example:

import numpy as np
arr = np.array([1, 2, 3])
print(arr.dtype)  # Output: int64 (or another int type)


##### Importance of Data Types in NumPy:

##### 1. Memory Management:

+ Fixed Size: NumPy arrays use fixed-size data types, so each element consumes a specific amount of memory (e.g., int32, float64).
+ Efficiency: Choosing the right data type (e.g., int8 vs. int64) helps control memory usage, especially when working with large datasets.


##### 2.Performance:

+ Faster Computations: NumPy operates more efficiently with consistent data types since it avoids the overhead of Python’s dynamic typing.
+ Vectorization: Operations on arrays are optimized for specific data types, speeding up numerical calculations.

#### 5. Define ndarray in NumPy and explain their key features. How do they differ from standard Python lists?

##### ndarray in NumPy:

An ndarray (N-dimensional array) is the core data structure of NumPy, used to store large, multi-dimensional arrays and matrices.



##### Key Features of ndarray:

 + Fixed Size: Once created, the size of an ndarray is fixed, meaning you cannot change its shape without creating a new array.
+ Homogeneous Data: All elements in an ndarray must have the same data type (e.g., all integers or all floats).
+ Efficient Memory Usage: ndarray uses contiguous memory, which makes it more memory-efficient than Python lists, especially for large datasets.
+ Supports Vectorized Operations: You can perform mathematical operations on entire arrays at once without looping, making computations much faster.
+ Multi-dimensional Support: Unlike Python lists, ndarray supports multiple dimensions, such as 1D, 2D (matrices), or higher.

##### Differences from Python Lists:

+ Memory Efficiency: ndarray consumes less memory because it uses fixed data types and contiguous memory storage.
+ Speed: ndarray is faster than Python lists due to optimized operations and no need for type checking during calculations.
+ Multi-dimensionality: ndarray can handle multiple dimensions easily, while Python lists require nested structures for the same.
+ Broadcasting: ndarray supports broadcasting, allowing operations on arrays of different shapes, which Python lists cannot do easily.


#### 6. Analyze the performance benefits of NumPy arrays over Python list for large- scale numerical operations.



#### Performance Benefits of NumPy Arrays Over Python Lists:

##### 1. Memory Efficiency:

+ Fixed Data Types: NumPy arrays store elements with a fixed data type, making them more memory-efficient compared to Python lists, which store pointers to objects of different types.
+ Contiguous Memory: NumPy arrays are stored in contiguous memory blocks, reducing memory overhead and allowing faster access.



##### 2. Faster Computations:

+ Vectorized Operations: NumPy can perform operations on entire arrays at once without loops (e.g., adding two arrays element-wise), which is much faster than iterating over Python lists.
+ C-Level Optimization: NumPy is implemented in C, allowing low-level optimizations and faster execution compared to Python's dynamic list implementation.

##### 3. Efficient Broadcasting:

+ Broadcasting: NumPy can handle operations between arrays of different shapes and sizes without extra code, making operations faster and simpler than manually resizing Python lists.

##### 4. Reduced Overhead:

+ Type Checking: Python lists require type checking at runtime for every element, whereas NumPy arrays skip this step since all elements have the same data type, improving speed.

##### conclusoin: 

For large-scale numerical operations, NumPy arrays offer significant performance advantages in terms of memory efficiency, speed, and optimized operations, making them far more suitable than Python lists for data-heavy computations.

#### 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

##### `vstack()` vs. `hstack()` in NumPy:

+ `vstack()` (Vertical Stack):

+ Stacks arrays vertically (row-wise).
+ Arrays are combined along a new row axis.
+ It requires the arrays to have the same number of columns.


+ `hstack()` (Horizontal Stack):

+ Stacks arrays horizontally (column-wise).
+ Arrays are combined along a new column axis.
+ It requires the arrays to have the same number of rows.

##### Example of `vstack()`:

In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.vstack((arr1, arr2))
print(result)


##### Example of `hstack()`:

In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.hstack((arr1, arr2))
print(result)


#### 8. Explain the differences between fliplr() and flipud() methods in Numpy, Including their effects on various array dimensions.

##### Differences Between `fliplr()` and `flipud()` in NumPy:

##### + `fliplr()` (Flip Left to Right):

+ Flips a 2D array horizontally, reversing the order of columns.
+ It only works on arrays with 2 or more columns.


##### + `flipud()` (Flip Up to Down):


+ Flips a 2D array vertically, reversing the order of rows.
+ It works on arrays with 2 or more rows.

##### Effects on Array Dimensions:

+ `fliplr()`:

+ The rows remain the same, but the columns are reversed.
+ Example: [ [1, 2], [3, 4] ] becomes [ [2, 1], [4, 3] ].


+ `flipud()`:

+ The columns remain the same, but the rows are reversed.
+ Example: [ [1, 2], [3, 4] ] becomes [ [3, 4], [1, 2] ].


#### 9. Discuss the functionally of the array_split() method in Numpy. How does it handle uneven splits?
                                    

##### Functionality of `array_split()` in NumPy:

The array_split() method in NumPy is used to divide an array into multiple smaller arrays. This is useful when you want to manage or process large datasets in smaller chunks.



##### How It Works:

In [ ]:
+ Input: You provide an array and specify how many pieces you want it to be split into, or you can give specific indices to split at.
+ Axis: You can choose to split the array along a specific direction (like rows or columns).


##### Handling Uneven Splits:

+ If the total number of elements in the array cannot be evenly divided by the number of pieces you want, array_split() will manage the leftover elements.
+ Most of the smaller arrays will have the same number of elements.
+ The last array will include any remaining elements.


#### 10. Explain the concepts of vectorizion and broadcasting in NumPy. How do they contribute to efficient array operations?

##### Vectorization in NumPy:

Vectorization refers to the process of performing operations on entire arrays instead of using loops to process individual elements. In NumPy, vectorized operations allow you to apply mathematical functions across all elements of an array at once.



+ Example:  If you want to add two arrays together, vectorization lets you do it in a single step:

import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = a + b  # Adds corresponding elements


+ Benefit: This makes calculations faster and cleaner because NumPy internally uses optimized C code for these operations.


##### Broadcasting in NumPy:

Broadcasting is a technique that allows NumPy to perform operations on arrays of different shapes. When performing an operation, NumPy automatically expands the smaller array to match the shape of the larger array.

+ Example: If you have a 1D array and a 2D array:

import numpy as np
a = np.array([1, 2, 3])  # Shape (3,)
b = np.array([[4, 5, 6],  # Shape (2, 3)
              [7, 8, 9]])
result = a + b  # a is broadcasted to (2, 3)


+ Benefit: Broadcasting simplifies code and allows for flexible operations without explicitly reshaping arrays, making it efficient for handling larger datasets.

###   Practical Question:

#### 1. Creat a 3x3 NumPy array with randam integers between 1 and 100. Then, interchange it's rows and coloums. 

In [ ]:
import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
array_3x3 = np.random.randint(1, 101, size=(3, 3))

# Interchange rows and columns (transpose the array)
array_transposed = array_3x3.T

print("Original array:")
print(array_3x3)
print("\nTransposed array:")
print(array_transposed)


#### 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [ ]:
import numpy as np

# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)

# Reshape into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Reshape into a 5x2 array
array_5x2 = array_2x5.reshape(5, 2)

print("1D array:", array_1d)
print("2x5 array:", array_2x5)
print("5x2 array:", array_5x2)


This code will give the following output:

1. 1D array: [0 1 2 3 4 5 6 7 8 9]

2. 2x5 array:

In [ ]:
[[0 1 2 3 4]
 [5 6 7 8 9]]


3. 5x2 array:

In [ ]:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


#### 3. Create a 4x4 NumPy array with random float values.Add a border of zeros around it, resulting in a 6*6array.

In [ ]:
import numpy as np

# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)

# Add a border of zeros around the array to make it 6x6
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print("Original 4x4 array:")
print(array_4x4)
print("\n6x6 array with zero border:")
print(array_6x6)


This code will:

1. Generate a 4x4 array with random float values between 0 and 1.
2. Add a border of zeros to expand it into a 6x6 array.







#### 4. Using Numpy, create an array of integers from 10 to 60 with a step of 5.

In [ ]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 65, 5)

print(array)


This code will output:

In [ ]:
[10 15 20 25 30 35 40 45 50 55 60]


#### 5. Create a Numpy array of strings ['python', 'numpy', 'pandas'.]. Apply different case transformations(uppercase, lowercase, title case,etc.) to each element. 

In [ ]:
import numpy as np

# Create a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(array)  # Convert to uppercase
lowercase_array = np.char.lower(array)  # Convert to lowercase
titlecase_array = np.char.title(array)  # Convert to title case

print("Original array:", array)
print("Uppercase:", uppercase_array)
print("Lowercase:", lowercase_array)
print("Title case:", titlecase_array)


This will output:

In [ ]:
Original array: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title case: ['Python' 'Numpy' 'Pandas']


#### 6. Generate a Numpy array of words. Insert a space between each character of every word in the array.

In [ ]:
import numpy as np

# Create a NumPy array of words
words_array = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_words_array = np.char.join(' ', words_array)

print("Original array:", words_array)
print("Spaced words array:", spaced_words_array)


This will output:

In [ ]:
Original array: ['python' 'numpy' 'pandas']
Spaced words array: ['p y t h o n' 'n u m p y' 'p a n d a s']


#### 7. Create two 2D Numpy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [ ]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Perform element-wise operations
addition = np.add(array1, array2)        # Element-wise addition
subtraction = np.subtract(array1, array2)  # Element-wise subtraction
multiplication = np.multiply(array1, array2)  # Element-wise multiplication
division = np.divide(array1, array2)     # Element-wise division

# Print results
print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("\nElement-wise addition:\n", addition)
print("Element-wise subtraction:\n", subtraction)
print("Element-wise multiplication:\n", multiplication)
print("Element-wise division:\n", division)


This will output:

In [ ]:
Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]

Element-wise addition:
 [[ 8 10 12]
 [14 16 18]]
Element-wise subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Element-wise multiplication:
 [[ 7 16 27]
 [40 55 72]]
Element-wise division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


#### 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.


In [ ]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract diagonal elements
diagonal_elements = np.diag(identity_matrix)

print("5x5 Identity Matrix:\n", identity_matrix)
print("\nDiagonal Elements:", diagonal_elements)


This will output:

In [ ]:
5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

Diagonal Elements: [1. 1. 1. 1. 1.]


#### 9. Generate a Numpy array of 100 random integers between 0 and 1000.Find and display all prime numbers in this array.


In [ ]:
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

# Function to check for prime numbers
def is_prime(num):
    if num <= 1:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

# Find all prime numbers in the array
prime_numbers = np.array([num for num in random_integers if is_prime(num)])

# Display the results
print("Random Integers:\n", random_integers)
print("\nPrime Numbers:\n", prime_numbers)


#### Explanation:
1. Generate Random Integers: The code creates an array of 100 random integers between 0 and 1000.
2. Prime Checking Function: The is_prime function checks if a number is prime.
3. Finding Primes: A list comprehension is used to extract prime numbers from the array.
4. Display Results: Finally, it prints the original random integers and the identified prime numbers.


#### 10. Create a Numpy array representing daily temperatures for a month. Calculate and display the weekly averages.



In [ ]:
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
# For example, let's generate random temperatures between 15 and 30 degrees Celsius
daily_temperatures = np.random.uniform(15, 30, size=30)

# Calculate the weekly averages (4 weeks)
weekly_averages = np.mean(daily_temperatures.reshape(-1, 7), axis=1)

# Display the results
print("Daily Temperatures for the Month:\n", daily_temperatures)
print("\nWeekly Averages:\n", weekly_averages)


##### Explanation:
1. Daily Temperatures: The code creates a 1D array of daily temperatures for 30 days using random values between 15 and 30 degrees Celsius.
2. Reshape for Weekly Averages: The reshape function is used to organize the temperatures into a shape of 4 weeks x 7 days. Since a month generally has 30 days, the last week will have 2 days; if you prefer, you can include 5 weeks (with 7 days) and take averages accordingly.
3. Calculate Averages: The np.mean function computes the average temperatures for each week.
4. Display Results: Finally, it prints the daily temperatures and the calculated weekly averages.
